usfbm_data_mart:

  target: dev
  outputs:

    dev:
      type: snowflake
      threads: 8
      query_tag: "DEV: USFBM Data Mart DBT project"
      
      account: "{{env_var('SNOW_USFBM_ACCOUNT')}}"
      user: "{{env_var('SNOW_USFBM_USERNAME_DEV')}}"
      password: "{{env_var('SNOW_USFBM_PASSWORD_DEV')}}"
      role: "{{env_var('SNOW_USFBM_ROLE_DEV')}}"
      
      warehouse: "{{env_var('SNOW_USFBM_WAREHOUSE_DEV')}}"
      database: "{{env_var('SNOW_USFBM_DATABASE_DEV')}}"
      schema: "{{env_var('SNOW_USFBM_SCHEMA_DEV')}}"

# -- change schema and db

    qa:
      type: snowflake
      threads: 8
      query_tag: "QA: USFBM Data Mart DBT project"
      
      account: "{{env_var('SNOW_USFBM_ACCOUNT')}}"
      user: "{{env_var('SNOW_USFBM_USERNAME_QA')}}"
      password: "{{ env_var('SNOW_USFBM_PASSWORD_QA')}}"
      role: "{{env_var('SNOW_USFBM_ROLE_QA')}}"
      
      warehouse: "{{env_var('SNOW_USFBM_WAREHOUSE_QA')}}"
      database: "{{env_var('SNOW_USFBM_DATABASE_QA')}}"
      schema: "{{env_var('SNOW_USFBM_SCHEMA_QA')}}"

# -- CHANGE TO QA

    prod:
      type: snowflake
      threads: 8
      query_tag: "PROD: USFBM Data Mart DBT project "
      
      account: "{{env_var('SNOW_USFBM_ACCOUNT')}}"
      user: "{{ env_var('SNOW_USFBM_USERNAME_PROD')}}"
      password: "{{env_var('SNOW_USFBM_PASSWORD_PROD')}}"
      role: "{{env_var('SNOW_USFBM_ROLE_PROD')}}"
      
      warehouse: "{{env_var('SNOW_USFBM_WAREHOUSE_PROD')}}"
      database: "{{ env_var('SNOW_USFBM_DATABASE_PROD')}}"
      schema: "{{env_var('SNOW_USFBM_SCHEMA_PROD')}}"