
version: 2

sources:

    - name: GOLD_RED_PRAIRIE
      description: "DB GOLD and SCHEMA RED_PRAIRIE sources"
      database: "GOLD{{ '_DEV' if target.name == 'dev' else '' }}{{ '_QA' if target.name == 'qa' else '' }}"
      schema: RED_PRAIRIE
      tables:
        - name: KVI_SUMMARY
        - name: KVI_ADJUSTMENTS
        - name: JOBCODE
        - name: WORKCATEGORY

    - name: GOLD_OMNITRACS
      description: "DB GOLD and SCHEMA OMNITRACS sources"
      database: "GOLD{{ '_DEV' if target.name == 'dev' else '' }}{{ '_QA' if target.name == 'qa' else '' }}"
      schema: OMNITRACS
      tables:
        - name: DRIVER_LOG_HDR

    - name: GOLD_XDMADM
      description: "DB GOLD and SCHEMA XDMADM sources"
      database: "GOLD{{ '_DEV' if target.name == 'dev' else '' }}{{ '_QA' if target.name == 'qa' else '' }}"
      schema: XDMADM
      tables:
        - name: DIV_CORP
        - name: TIME_CORP