version: 2

models:
  - name: DIM_DATE
    description: Calendar dimension that shows all calendar attributes for a given calendar date from 2019 - 2035
    columns: 
      - name: DIM_DATE_SK
        description: Primary Key for Calendar Dimension for each Day
        tests:
          - dbt_expectations.expect_column_values_to_be_unique
      - name: CLNDR_DT
        detail: Calendar Date
        description: Calendar Date in YYYY-MM-DD format
      - name: CLNDR_DAY_NM
        description: Name of the Calendar Date (e.g. SUNDAY, MONDAY, etc.)
      - name: CLNDR_MTH_NM
        description: Name of the month for the Calendar Date (e.g. JANUARY, FEBRUARY, etc.)
      - name: CLNDR_YR
        description: Year of the Calendar Date (e.g. 2009, 2010)
      - name: CLNDR_DAY_OF_WK
        description: Integer value calendar Day of the Week from 1- 7 where 1 is Sunday, 2 is Monday, etc.
      - name: CLNDR_DAY_OF_MTH
        description: Integer value of the day within the month (e.g. 28, 29, 30)
      - name: CLNDR_MTH_OF_YR
        description: Integer value fo the Fiscal Month Name for the Calendar Date in the Fiscal Year (1 is January, 2 is February, 3 is March, etc.)
      - name: CLNDR_YR_QTR
        description: String composite of the Calendar Days Year and Quarter (e.g. 2020Q1, 2020Q2, 2020Q3, etc.)
      - name: CLNDR_YR_MTH
        description: Integer composite of the Calendar Days Year and Month (e.g. 202012, 202101, 202102, etc.)
      - name: FISC_YR
        description: Integer Fiscal Year for the Calendar Date (e.g. 2020, 2021, 2022)
      - name: FISC_DAY_OF_YR
        description: Integer Fiscal Day Of the Year for the Calendar Date (e.g. 1, 2, … 365, etc.)
      - name: FISC_DAY_NM
        description: Fiscal Day Name of the Calendar Date (e.g. SUNDAY, MONDAY, etc.)
      - name: FISC_WK_OF_YR
        description: Integer value of the Fiscal Week in the Year for a Calendar Date (e.g. 49, 50, 51, 52, etc.)
      - name: FISC_WK_OF_PRD
        description: Integer value of the Fiscal Week in the Period for a Calendar Date (e.g. 49, 50, 51, 52, etc.)
      - name: FISC_MTH_OF_YR
        description: Integer value fo the Fiscal Month Name for the Calendar Date in the Fiscal Year (1 is January, 2 is February, 3 is March, etc.)
      - name: FISC_MTH_NM
        description: Name of the Fiscal Month for the Calendar Date (e.g. JANUARY, FEBRUARY, etc.)
      - name: FISC_QTR_OF_YR
        description: String value of the Fiscal Quarter for the Calendar Date (e.g. Q1, Q2, Q3, Q4)
      - name: FISC_HALF_OF_YR
        description: String value of the Fiscal Half for the Calendar Date (e.g. H1, H2)
      - name: FISC_YR_QTR
        description: String composite of the Fiscal Year and Fiscal Quarter for the Calendar Date (e.g. 2020Q1, 2020Q2, 2020Q3, etc.)
      - name: FISC_YR_MTH
        description: Integer composite of the Fiscal Year and Fiscal Month for the Calendar Date (e.g. 202012, 202101, 202102, etc.)
      - name: FISC_YR_WK
        description: Integer composite of the Fiscal Year and Fiscal Week for the Calendar Date (e.g. 202022, 202023, 202024, etc.)
      - name: FISC_WKS_THIS_PD
        description: Integer value that shows total number of Fiscal Weeks within the Period
      - name: TM_SK_YRAGO
        description: Same Day Prior Year for a given Calendar Date surrogate key
      - name: CLNDR_DT_YRAGO
        description: Same Day Prior Year for a given Calendar Date
      - name: FISC_PRD_NM
        description: Fiscal Period Name for a given Period
      - name: GRG_CLNDR_DT_YRAGO
        description: Same Day Prior Year for a given Calendar Date in the Gregorian Calendar
      - name: CLNDR_WK_STRT_DT
        description: Week Start Date for the Calendar Date
      - name: CLNDR_WK_END_DT
        description: Calendar Week End Date for the Calendar Date
      - name: CLNDR_WK_NM
        description: String Composite that shows the Week Start Date and Week End Date (e.g. 05/16/2021 - 05/22/2021)
      - name: CLNDR_MTH_NM_YR
        description: String composite of the Calendar Month Name with the Calendar Year (e.g. MARCH 2022, APRIL 2022, etc.)
      - name: GRG_CLNDR_YR_MTH_YRAGO
        description: Same Month Prior Year for a given Calendar Date in the Gregorian Calendar
      - name: LIC_THURS_DT
        description: Last Invoice Cost Thursday Date
      - name: FST_BUS_DT_NEXT_MONTH
        description: Date value for the first business day of the next Month for a given calendar date
      - name: ORD_GD_GEN_DT
        description: Order Goods General Date
      - name: MON_AFTER_LIC_THURS_DT
        description: Monday after Last Invoice Cost Thursday Date
      - name: CLNDR_DT_WKAGO
        description: Same Day Prior Week for a given calendar date      
  - name: DIM_JOBCODE
    columns:
      - name: DIRECT
        description: Direct Hours Flag for Job Code Type and Warehouse Code
      - name: JOBCODE_CD
        description: Job Code
      - name: WH_CD
        description: Warehouse Code  
      - name: JOBCODE_ID
        description: Job Code ID
      - name: SRC_ID
        description: Source ID for the event                    
      - name: DIM_JOBCODE_SK
        description: Primary Key for the Job Code - derived from Business Key set Job Code ID and Warehouse Code                                   
  - name: DIM_MARKET
    columns:
      - name: DIM_MARKET_SK
        description: Primary Key for the Market - derived from Business Key set of Warehouse Code
    columns:
      - name: WH_CD
        description: Warehouse Code for the respective market  
    columns:
      - name: DIV_TYP_CD
        description: Division Type Code for the respective market  
    columns:
      - name: DIV_ID
        description: A 4-digit number given to each Division  
    columns:
      - name: DIV_NM
        description: Division name of the market 
    columns:
      - name: RGN_NM
        description: Region name that the market is located  
    columns:
      - name: RGN_CD
        description: Region code that the market is located  
    columns:
      - name: CMPNY_DESC
        description: Company description for the respective market, e.g. Broadline
    columns:
      - name: AREA_NM
        description: Name of the area that the market is located  
    columns:
      - name: DIV_NM_CD_NBR
        description: Combination of the Division Name, Divison Code, and Division Number for the respective market  
    columns:
      - name: PRCS_SYS
        description: Process source system for the respective market  
    columns:
      - name: ZIP_CD
        description: Zip code where the market is located                                                                                         
  - name: DIM_WORK_CATEGORY
    columns:
      - name: WCT_ID
        description: Work Category ID for the respective Work Category and Warehouse CD  
      - name: WH_CD
        description: Warehouse Code
      - name: WCT_NAME
        description: WWork Category Name for the respective Work Category and Warehouse Name
      - name: DIM_WORK_CATEGORY_SK                        
        description: Primary Key for the Market - derived from Business Key set of Warehouse Code and Work Category ID
  
  
