version: 2

models:
  - name: DIM_DATE
    columns: 
      - name: DIM_DATE_PK
        tests:
          - dbt_expectations.expect_column_values_to_be_unique
      # - name: DIM_DATE_PK
      #   tests:
      #     - dbt_expectations.expect_column_values_to_not_be_null
      # - name: DIM_DATE_PK
      #   tests:
      #     - dbt_expectations.expect_column_to_exist
      # - name: DIM_DATE_PK
      #   tests:
      #       - dbt_expectations.expect_table_row_count_to_be_between:
      #           minimum: 1
      #           maximum: 4


